annotations:
  artifacthub.io/changes: |
    - "feat(flux,source-controller): add possibility to use a pvc for 'Persistent storage for Flux internal artifacts'"
apiVersion: v2
appVersion: 2.6.4
description: A Helm chart for flux2
name: flux2
sources:
- https://github.com/fluxcd-community/helm-charts
type: application
version: 2.17.0
